In [1]:
import h2o 
from h2o.automl import H2OAutoML

In [2]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
; OpenJDK 64-Bit Server VM Temurin-25.0.2+10 (build 25.0.2+10-LTS, mixed mode, sharing)
  Starting server from C:\Users\Pichau\OneDrive\Documentos\GitHub\automl_tunning\.venv\Lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\Pichau\AppData\Local\Temp\tmpfeneethe
  JVM stdout: C:\Users\Pichau\AppData\Local\Temp\tmpfeneethe\h2o_Pichau_started_from_python.out
  JVM stderr: C:\Users\Pichau\AppData\Local\Temp\tmpfeneethe\h2o_Pichau_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------
H2O_cluster_uptime:         01 secs
H2O_cluster_timezone:       America/Sao_Paulo
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.9
H2O_cluster_version_age:    2 months and 25 days
H2O_cluster_name:           H2O_from_python_Pichau_bdilyk
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.957 Gb
H2O_cluster_total_cores:    0
H2O_cluster_allowed_cores:  0
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.14.0 final
--------------------------  -----------------------------

In [3]:
df = h2o.import_file('insurance.csv')

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [4]:
df

  C1  GoodStudent    Age         SocioEcon    RiskAversion    VehicleYear    ThisCarDam    RuggedAuto    Accident    MakeModel    DrivQuality    Mileage     Antilock    DrivingSkill    SeniorTrain    ThisCarCost    Theft    CarValue    HomeBase    AntiTheft    PropCost     OtherCarCost    OtherCar    MedCost    Cushioning    Airbag    ILiCost    DrivHist
----  -------------  ----------  -----------  --------------  -------------  ------------  ------------  ----------  -----------  -------------  ----------  ----------  --------------  -------------  -------------  -------  ----------  ----------  -----------  -----------  --------------  ----------  ---------  ------------  --------  ---------  ----------
   1  False          Adult       Prole        Adventurous     Older          Moderate      EggShell      Mild        Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        True        Thousand   Poor          False     Thousand   Many
   2  False          Senior      Prole        Cautious        Current        None          Football      None        Economy      Normal         TwentyThou  False       Normal          True           Thousand       False    TenThou     City        True         Thousand     Thousand        True        Thousand   Good          True      Thousand   Zero
   3  False          Senior      UpperMiddle  Psychopath      Current        None          Football      None        FamilySedan  Excellent      Domino      True        Normal          False          Thousand       False    TwentyThou  City        False        Thousand     Thousand        False       Thousand   Good          True      Thousand   One
   4  False          Adolescent  Middle       Normal          Older          None          EggShell      None        Economy      Normal         FiftyThou   False       Normal          False          Thousand       False    FiveThou    Suburb      False        Thousand     Thousand        True        Thousand   Fair          False     Thousand   Zero
   5  False          Adolescent  Prole        Normal          Older          Moderate      Football      Moderate    Economy      Poor           FiftyThou   False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        False       Thousand   Fair          False     Thousand   Many
   6  False          Adult       UpperMiddle  Normal          Current        Moderate      EggShell      Moderate    SportsCar    Poor           FiftyThou   True        SubStandard     False          HundredThou    False    TwentyThou  Suburb      True         HundredThou  HundredThou     True        TenThou    Poor          True      Thousand   Many
   7  False          Senior      UpperMiddle  Normal          Current        Mild          Football      Mild        Economy      Poor           FiveThou    False       SubStandard     False          TenThou        False    TenThou     Secure      True         TenThou      Thousand        False       Thousand   Excellent     True      Thousand   Many
   8  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    TenThou     City        False        Million      HundredThou     True        Thousand   Fair          False     Thousand   Many
   9  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        HundredThou  TenThou         False       TenThou    Poor          False     Thousand   Many
  10  True           Adolescent  Prole        Cautious        Older          Severe        Football      Severe      FamilySedan  Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        True         HundredThou  HundredThou     True        Thousand   Good          False     Thousand   Many
[20000 rows x 28 columns]

In [ ]:
#separando o modelo o target
df =  df.drop('C1')

In [ ]:
#separando em treino e teste
treino, teste =  df.split_frame(ratios=[0.7], seed = 0)

In [10]:
models_automl = H2OAutoML(max_runtime_secs= 180, sort_metric='AUTO')
models_automl.train(y="Accident", training_frame=treino)

AutoML progress: |
19:03:35.791: AutoML: XGBoost is not available; skipping it.
19:03:35.938: GLM_1_AutoML_2_20260218_190335 [GLM def_1] failed: java.lang.ArrayIndexOutOfBoundsException: Index 83 out of bounds for length 83

███████████████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OGradientBoostingEstimator : Gradient Boosting Machine
Model Key: GBM_1_AutoML_2_20260218_190335


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    63                 252                         259104                 8            15           13.5675       27            85            77.25

ModelMetricsMultinomial: gbm
** Reported on train data. **

MSE: 0.025219095367646972
RMSE: 0.15880521202922457
LogLoss: 0.08511574348521178
Mean Per-Class Error: 0.09527058937830125
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error       Rate
------  ----------  ------  --------  ----------  ------------
1009    56          154     3         0.174304    213 / 1.222
30      928         4       166       0.177305    200 / 1.128
12      0           10040   0         0.00119379  12 / 10.052
0       47          0       1615      0.0282792   47 / 1.662
1051    1031        10198   1784      0.0335609   472 / 14.064

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.966439
2    0.999502
3    1
4    1

ModelMetricsMultinomial: gbm
** Reported on cross-validation data. **

MSE: 0.03790043703735343
RMSE: 0.19468034579112867
LogLoss: 0.13236324908545216
Mean Per-Class Error: 0.1377400438088818
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error       Rate
------  ----------  ------  --------  ----------  ------------
931     93          196     2         0.238134    291 / 1.222
63      838         4       223       0.257092    290 / 1.128
28      0           10024   0         0.00278552  28 / 10.052
0       88          0       1574      0.0529483   88 / 1.662
1022    1019        10224   1799      0.0495592   697 / 14.064

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.950441
2    0.998365
3    0.999645
4    1

Cross-Validation Metrics Summary:
                         mean       sd          cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ---------  ----------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.95037    0.00406065  0.950231      0.948454      0.944899      0.95272       0.955548
aic                      nan        0           nan           nan           nan           nan           nan
auc                      nan        0           nan           nan           nan           nan           nan
err                      0.0496299  0.00406065  0.0497689     0.0515464     0.0551013     0.0472805     0.0444523
err_count                139.6      11.4368     140           145           155           133           125
loglikelihood            nan        0           nan           nan           nan           nan           nan
logloss                  0.133264   0.0101005   0.130741      0.136262      0.148986      0.127849      0.122484
max_per_class_error      0.264009   0.0290727   0.252033      0.294931      0.295652      0.23913       0.238298
mean_per_class_accuracy  0.862439   0.0118276   0.861002      0.856377      0.846809      0.871881      0.876125
mean_per_class_error     0.137561   0.0118276   0.138998      0.143623      0.153191      0.128119      0.123875
mse                      0.0379887  0.00256455  0.0372214     0.0394614     0.0416828     0.036125      0.035453
pr_auc                   nan        0           nan           nan           nan           nan           nan
r2                       0.927982   0.00439479  0.929403      0.926075      0.921275      0.93218       0.93098
rmse                     0.194819   0.0065344   0.192928      0.198649      0.204164      0.190066      0.18829

Scoring History:
    timestamp            duration    number_of_trees    training_rmse    training_logloss    training_classification_error    training_auc    training_pr_auc
--  -------------------  ----------  -----------------  ---------------  ------------------  -------------------------------  --------------  -----------------
    2026-02-18 19:03:44  8.436 sec   0                  0.75             1.38629             0.442904                         nan             nan
    2026-02-18 19:03:44  8.554 sec   5                  0.473274         0.644789            0.0507679                        nan             nan
    2026-02-18 19:03:44  8.656 sec   10                 0.313988         0.364944            0.0504835                        nan             nan
    2026-02-18 19:03:44  8.756 sec   15                 0.242443         0.24145             0.0501991                        nan             nan
    2026-02-18 19:03:44  8.883 sec   20                 0.212917         0.181433            0.049417                         nan             nan
    2026-02-18 19:03:44  8.993 sec   25                 0.200096         0.15106             0.0479238                        nan             nan
    2026-02-18 19:03:45  9.104 sec   30                 0.192086         0.132593            0.0472127                        nan             nan
    2026-02-18 19:03:45  9.214 sec   35                 0.185883         0.120296            0.0451507                        nan             nan
    2026-02-18 19:03:45  9.326 sec   40                 0.180384         0.111012            0.043302                         nan             nan
    2026-02-18 19:03:45  9.434 sec   45                 0.17516          0.103864            0.0408134                        nan             nan
    2026-02-18 19:03:45  9.538 sec   50                 0.170813         0.098093            0.0394625                        nan             nan
    2026-02-18 19:03:45  9.646 sec   55                 0.165718         0.0923445           0.0363339                        nan             nan
    2026-02-18 19:03:45  9.763 sec   60                 0.160992         0.0874721           0.0340586                        nan             nan
    2026-02-18 19:03:45  9.826 sec   63                 0.158805         0.0851157           0.0335609                        nan             nan

Variable Importances:
variable      relative_importance    scaled_importance       percentage
------------  ---------------------  ----------------------  ----------------------
ThisCarDam    17280.755859375        1.0                     0.6912422629454862
OtherCarCost  2087.5                 0.12079911416996891     0.08350145304065945
DrivingSkill  1594.719482421875      0.09228297045564254     0.0637898893290898
ThisCarCost   1520.9249267578125     0.08801263898029633     0.06083805573654415
DrivQuality   744.6859741210938      0.043093368147846       0.02978795731646
RuggedAuto    505.2831726074219      0.02923964534417632     0.020211678615431886
PropCost      316.37823486328125     0.018308124797194132    0.012655349615100842
MedCost       198.9518585205078      0.011512914142153928    0.007958212824719573
Mileage       123.08208465576172     0.007122494273824737    0.004923369059654879
Cushioning    88.79217529296875      0.005138211315264779    0.003551748817055728
---           ---                    ---                     ---
ILiCost       31.13167953491211      0.0018015230229656205   0.0012452888511431486
Age           30.809452056884766     0.0017828764151060152   0.0012323995277300178
OtherCar      28.258893966674805     0.001635281129867016    0.0011303754287613275
VehicleYear   24.286415100097656     0.0014054023618950678   0.0009714735089852777
Antilock      24.05148696899414      0.001391807578598823    0.0009620762202153279
Airbag        21.844703674316406     0.0012641057979223412   0.0008738033523583485
AntiTheft     12.195125579833984     0.000705705565142742    0.00048781351182249213
GoodStudent   0.9438307881355286     5.4617448207480464e-05  3.775388849524668e-05
SeniorTrain   0.3959626257419586     2.2913501525290314e-05  1.5838780646346526e-05
Theft         0.0                    0.0                     0.0
[26 rows x 4 columns]


[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [11]:
#conferindo modelos gerados
ranking = models_automl.leaderboard
ranking = ranking.as_data_frame()
ranking

c:\Users\Pichau\OneDrive\Documentos\GitHub\automl_tunning\.venv\Lib\site-packages\h2o\frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

,model_id,mean_per_class_error,logloss,rmse,mse
0,GBM_1_AutoML_2_20260218_190335,0.137740,0.132363,0.194680,0.037900
1,StackedEnsemble_AllModels_1_AutoML_2_20260218_...,0.138675,0.133926,0.197357,0.038950
2,StackedEnsemble_BestOfFamily_2_AutoML_2_202602...,0.138799,0.131479,0.196067,0.038442
3,StackedEnsemble_BestOfFamily_1_AutoML_2_202602...,0.139889,0.134550,0.197414,0.038972
4,GBM_grid_1_AutoML_2_20260218_190335_model_3,0.140050,0.138293,0.197835,0.039139
5,StackedEnsemble_AllModels_3_AutoML_2_20260218_...,0.140204,0.131181,0.195072,0.038053
6,GBM_grid_1_AutoML_2_20260218_190335_model_9,0.140661,0.128561,0.193430,0.037415
7,GBM_grid_1_AutoML_2_20260218_190335_model_5,0.141031,0.133469,0.195816,0.038344
8,DRF_1_AutoML_2_20260218_190335,0.141203,0.168214,0.201455,0.040584
9,StackedEnsemble_AllModels_2_AutoML_2_20260218_...,0.141208,0.131469,0.195893,0.038374
10,GBM_grid_1_AutoML_2_20260218_190335_model_8,0.141229,0.128924,0.193278,0.037356
11,GBM_grid_1_AutoML_2_20260218_190335_model_2,0.141255,0.146526,0.202299,0.040925
12,GBM_2_AutoML_2_20260218_190335,0.141355,0.137554,0.198614,0.039447
13,GBM_grid_1_AutoML_2_20260218_190335_model_7,0.141431,0.138022,0.199009,0.039605
14,GBM_3_AutoML_2_20260218_190335,0.141650,0.140737,0.200117,0.040047
15,GBM_grid_1_AutoML_2_20260218_190335_model_1,0.141851,0.141075,0.200559,0.040224
16,DeepLearning_1_AutoML_2_20260218_190335,0.142017,0.139504,0.199778,0.039911
17,GBM_grid_1_AutoML_2_20260218_190335_model_10,0.142295,0.190113,0.219839,0.048329
18,GBM_5_AutoML_2_20260218_190335,0.142589,0.136649,0.197822,0.039134
19,GBM_4_AutoML_2_20260218_190335,0.143445,0.148357,0.202642,0.041064
20,GBM_grid_1_AutoML_2_20260218_190335_model_6,0.145744,0.165524,0.210725,0.044405
21,GBM_grid_1_AutoML_2_20260218_190335_model_4,0.147682,0.139464,0.199172,0.039669
22,GBM_grid_1_AutoML_2_20260218_190335_model_11,0.148836,1.129653,0.676363,0.457467
23,DeepLearning_grid_1_AutoML_2_20260218_190335_m...,0.149866,0.195085,0.197403,0.038968
24,XRT_1_AutoML_2_20260218_190335,0.152403,0.575863,0.433677,0.188076
25,DeepLearning_grid_1_AutoML_2_20260218_190335_m...,0.154238,0.165751,0.213342,0.045515

In [13]:
prever = models_automl.leader.predict(teste)
prever

gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

predict           Mild     Moderate         None       Severe
---------  -----------  -----------  -----------  -----------
None       0.000228829  6.90145e-05  0.999639     6.29286e-05
Moderate   0.0035945    0.987284     0.000326892  0.00879438
Severe     0.00174887   0.0854429    0.00080301   0.912005
None       0.000618071  0.000112336  0.999162     0.000107695
Severe     0.00293143   0.338527     0.00193739   0.656604
None       0.00623443   0.000476269  0.993103     0.000185918
Mild       0.969377     0.025716     0.00296965   0.0019369
None       0.000156289  0.000100179  0.999684     5.94829e-05
None       0.001118     0.000148246  0.998582     0.000151579
Severe     0.0010451    0.202878     0.00085196   0.795224
[5936 rows x 5 columns]